# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chat_pb2 as chat__pb2


class SpartanMessengerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.LoginUser = channel.unary_unary(
        '/messenger.SpartanMessenger/LoginUser',
        request_serializer=chat__pb2.User.SerializeToString,
        response_deserializer=chat__pb2.Groups.FromString,
        )
    self.ReceiveMessage = channel.unary_stream(
        '/messenger.SpartanMessenger/ReceiveMessage',
        request_serializer=chat__pb2.Message.SerializeToString,
        response_deserializer=chat__pb2.Message.FromString,
        )


class SpartanMessengerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def LoginUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReceiveMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SpartanMessengerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'LoginUser': grpc.unary_unary_rpc_method_handler(
          servicer.LoginUser,
          request_deserializer=chat__pb2.User.FromString,
          response_serializer=chat__pb2.Groups.SerializeToString,
      ),
      'ReceiveMessage': grpc.unary_stream_rpc_method_handler(
          servicer.ReceiveMessage,
          request_deserializer=chat__pb2.Message.FromString,
          response_serializer=chat__pb2.Message.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'messenger.SpartanMessenger', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
